
---
name: Build and push to Registry

on:
  push:
    branches: main
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          tags: yeehaw123/ubuntu_govc:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
